name: Debug Angular Build

on:
  push:
    branches: [ master ]

jobs:
  debug-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build Angular app
      run: |
        echo "=== Starting Angular Build ==="
        npm run build -- --configuration production --base-href ./
        echo "=== Build Successful ==="
      
    - name: Show build output
      run: |
        echo "=== Build Output Structure ==="
        find . -name "index.html" -type f
        echo "=== dist folder contents ==="
        ls -la dist/ || echo "No dist folder"
        ls -la dist/sales-dashboard/ || echo "No sales-dashboard folder"